theme: jekyll-theme-minimal
permalink: /resources/:title
name: BFEA
url: http://www.bfea.co.uk
google_analytics: UA-86474387-2

nav-background: #B40604
nav-font: #fff
jumbotron-background: #ECEEEF
jumbotron-font: #fff

plugins:
- jekyll-seo-tag
