theme: jekyll-theme-minimal
permalink: pretty
url: https://krussll.github.io/boilerplate/
style:
  nav:
    background: #B40604
    font: #ffffff
  jumbotron:    
    background: #ECEEEF
    font: #ffffff
